Failure message

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -4,7 +4,7 @@ on:
   pull_request:
     types: [opened, synchronize]
     paths:
-      - 'Gemfile.lock'
+      - "Gemfile.lock"
   workflow_dispatch:
 
 permissions:
@@ -20,25 +20,30 @@ jobs:
   job:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v3
-      with:
-        ref: ${{ github.head_ref }}
+      - uses: actions/checkout@v3
+        with:
+          ref: ${{ github.head_ref }}
 
-    - name: Echo git status
-      run: |
+      - name: Echo git status
+        run: |
           output=$(git status)
           echo $output
 
-    - name: Echo git log
-      run: |
+      - name: Echo git log
+        run: |
           output=$(git log -1 HEAD)
           echo $output
 
-    - name: Try to checkout
-      run: |
+      - name: Try to checkout
+        run: |
           git checkout ${{ github.head_ref }}
 
-    - name: sleep
-      run: |
-          echo ${{ github.workflow }}-${{ github.head_ref }}
-          sleep 600
+      - name: Failure
+        id: setup
+        run: |
+          exit 1
+
+      - name: Failure message
+        if: ${{ failure() && steps.setup.conclusion == 'failure' }}
+        run: |
+          echo "Failed during setup"
